theme = "nightfox"

[editor]
line-number = "relative"
mouse = false
scroll-lines = 5
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-h = ["move_char_left", "move_char_left", "move_char_left", "move_char_left", "move_char_left"]
C-j = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
C-k = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
C-l = ["move_char_right", "move_char_right", "move_char_right", "move_char_right", "move_char_right"]
C-r = ":config-reload"
C-n = ["select_mode", "move_char_right", "move_prev_word_start", "move_next_word_start", "search_selection"]

[keys.normal.g]
a = "code_action"
